---
title: ''
author: "Fabiana eTelma"
date: "8 de abril de 2017"
output: pdf_document
---
Questão 2:

Geramos amostras de uma distribuição de interesse a partir da geração de de uma distribuição conhecida e então, rejeitando um subconjunto gerado. O mecanismo de rejeição é construído de forma que, a amostra que será aceita segue a distribuição de interesse.
Queremos gerar valores aleatórios de uma densidade de probabilidade $f$ definida em um algum conjunto $X$.
 Seja $g$ uma densidade em $X$ a partir da qual sabemos gerar valores aleatórios e com a propriedade de que
$f(X) < c*g(X)$, para todo $x \in X$ e alguma constante $c$.

Geramos um elemento $x$ a partir da densidade $g$ e aceitamos o elemento com probabilidade $f(x)/cg(X)$, ou seja,
$$
P(\text{Aceitar}|Y) = P\left(U < \frac{f(Y)}{cg(Y)}|Y\right) = \frac{f(Y)}{cg(Y)}.
$$
Note ainda que a probabilidade total de aceitar $Y$ pode ser calculada da seguinte maneira:
$$
\sum_{n}P(\text{Aceitar}|y)P(Y=y)=\sum_{n}\frac{f(y)}{cg(y)}g(y)=\frac{1}{c}.
$$
Agora possuimos todos os elementos para mostrar, pelo menos no caso discreto, que o método de aceitação e rejeição gera, de fato, números aleatórios da distribuição de interesse. Para a prova utilizamos o teorema de Bayes.

Suponha um $k$ qualquer de modo que $f(k)>0$, então pelo teorema de Bayes temos que: 
$$
P(k|\text{Aceitar})=\frac{P(\text{Aceitar}|k)g(k)}{P(\text{Aceitar})} = \frac{[f(k)/(cg(k))]g(k)]}{1/c} = f(k)
$$

Este método pode ser implementado ao gerar um elemento $u$ distribuido uniformemente em (0,1) e então, aceitamos se $u < f(x)/cg(x)$. 
Se $x$ é rejeitado, um novo candidato é amostrado de $g$ e repetimos o teste de aceitação. 
O processo se repete até que o teste de aceitação gere a quantidade desejada de números aleatórios; os valores aceitos são elementos com distribuição $f$.

Algoritmo
O algoritmo do método de aceitação-rejeição pode ser apresentado nos passos abaixo.
\begin{enumerate}
\item{Simula-se o valor $x$ com densidade $g$ }
\item{Gera-se um número aleatório $u \sim \text{Unif}(0,1)$}
\item{Se $u < f(x)/cg(x)$, aceita-se o valor e para. Caso contrário, retorna-se ao passo 1.}
\end{enumerate}